on:
  push:
    
  workflow_dispatch:
  
env:
  PROJECT_NAME: "Monte Carlo estimation of pi"
  AUTHOR: "Kaustubh Daruri"
  PI: 3.142857
  INPUT_FILE_NAME: get_pi.cpp
  COMPILED_FILE_NAME: get_pi_o
  OUTPUT_FILE_NAME: data.txt
  
  
  
jobs:
  stage_1:
    name: initial_testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: initial check
        run: |
          echo "Initializing....."
          echo "3"
          echo "2"
          echo "1"
          echo "checking directory"
          ls
        
      - name: print project name
        run: |
          echo "$PROJECT_NAME"
          
      - name: list_variables
        run: |
          printenv
        
        
  stage_2:
    name: "Compile and run"
    runs-on: ubuntu-latest
    needs: 
      - stage_1
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: check gcc version
        run: |
          whereis gcc
          which gcc
          gcc --version
          
      - name: compile 
        run: |
          g++ $INPUT_FILE_NAME -o $COMPILED_FILE_NAME -lm
          
      - name: check contents
        run: |
          ls
      
      - name: run
        run: |
          ./$COMPILED_FILE_NAME >> $OUTPUT_FILE_NAME
          cat $OUTPUT_FILE_NAME
          
      - name: check contents
        run: |
          ls
          
      
      
          
      
      
          
          
          
    
