on:
  push:
    
  workflow_dispatch:
  
env:
  PROJECT_NAME: "Monte Carlo estimation of pi"
  AUTHOR: "Kaustubh Daruri"
  PI: 3.142857
  
  
  
jobs:
  stage_1:
    name: initial_testing
    runs-on: ubuntu-latest
    steps:
      - name: initial check
        run: |
          echo "Initializing....."
          echo "3"
          echo "2"
          echo "1"
        
      - name: print project name
        run: |
          echo "$PROJECT_NAME"
          
      - name: list_variables
        run: |
          printenv
        
        
#   stage_2:
#     runs-on: ubuntu-latest
#     needs: 
#       - stage_1
#     name: "Compile code"
#     steps: 
#       - name: install_gcc
#         run: |
#           
    
