on:
  push:
    branches:
    - main
    
  workflow_dispatch:
  
env:
  PROJECT_NAME: "Monte Carlo estimation of pi"
  
  
jobs:
  stage_1:
    name: initial_testing
    runs-on: ubuntu-latest
    steps:
      - name: check
        run: |
          echo "Initializing....."
          echo "3"
          echo "2"
          echo "1"
        
      - name: print_project
        run: echo "$PROJECT_NAME"
        
        
#   stage_2:
#     runs-on: ubuntu-latest
#     needs: 
#       - stage_1
#     name: "Compile get pi"
#     steps: 
#       - name: install_gcc
#         run: |
#           
    
