on:
  push:
    
  workflow_dispatch:
  
env:
  PROJECT_NAME: "Monte Carlo estimation of pi"
  AUTHOR: "Kaustubh Daruri"
  PI: 3.142857
  
  
  
jobs:
  stage_1:
    name: initial_testing
    runs-on: ubuntu-latest
    steps:
      - name: initial check
        run: |
          echo "Initializing....."
          echo "3"
          echo "2"
          echo "1"
        
      - name: print project name
        run: |
          echo "$PROJECT_NAME"
          
      - name: list_variables
        run: |
          printenv
        
        
  stage_2:
    name: "Compile code"
    runs-on: ubuntu-latest
    needs: 
      - stage_1
    steps: 
      - name: check gcc version
        run: |
          whereis gcc
          which gcc
          gcc -version
          
      - name: compile 
        run: |
          g++ get_pi.cpp -o get_pi_o -lm
          ls
          
          
          
    
