on:
  push:
    
  workflow_dispatch:
  
env:
  PROJECT_NAME: "Monte Carlo estimation of pi"
  AUTHOR: "Kaustubh Daruri"
  PI: 3.142857
  INPUT_FILE_NAME: get_pi.cpp
  COMPILED_FILE_NAME: get_pi_o
  OUTPUT_FILE_NAME: answer.txt
  TEST_INPUT_FILE_NAME: tests_for_getpi.cpp
  TEST_COMPILED_FILE_NAME: tests_for_getpi_o
  TEST_OUTPUT_FILE_NAME: test_result.txt
  
  
  
jobs:
  stage_1:
    name: initial_testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: initial check
        run: |
          echo "Initializing....."
          echo "3"
          echo "2"
          echo "1"
          echo "checking directory"
          ls
        
      - name: print project name
        run: |
          echo "$PROJECT_NAME"
          
      - name: list_variables
        run: |
          printenv
        
        
  stage_2:
    name: "Compile and run"
    runs-on: ubuntu-latest
    needs: 
      - stage_1
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: check gcc version
        run: |
          whereis gcc
          which gcc
          gcc --version
          
      - name: compile 
        run: |
          g++ $INPUT_FILE_NAME -o $COMPILED_FILE_NAME -lm
      
      - name: run
        run: |
          ./$COMPILED_FILE_NAME >> $OUTPUT_FILE_NAME
          cat $OUTPUT_FILE_NAME
          
      - name: upload output file
        uses: actions/upload-artifact@v3
        with:
          name: answer.txt
          path: answer.txt
          
  stage_3:
      name: "testing"
      runs-on: ubuntu-latest
      needs:
        - stage_2
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Download a Build Artifact
          uses: actions/download-artifact@v2.1.1
          with:
            name: answer.txt
            
        - name: check file content
          run: |
            cat answer.txt
        
        - name: check gcc version
          run: |
            whereis gcc
            which gcc
            gcc --version

        - name: compile 
          run: |
            g++ $TEST_INPUT_FILE_NAME -o $TEST_COMPILED_FILE_NAME -lm

        - name: run
          run: |
            ./$TEST_COMPILED_FILE_NAME >> $TEST_OUTPUT_FILE_NAME
            cat $TEST_OUTPUT_FILE_NAME
          
          
      
  
          
      
      
          
      
      
          
          
          
    
